### ISSUE TITLE
Transactions visible to all users

### ISSUE THREAD

**Issue by ssorallen** [Kellyreid/mtgtest#1]
`set_transaction` is looking up the Transaction regardless of the user: https://github.com/Kellyreid/mtgtest/blob/master/app/controllers/transactions_controller.rb#L70

That method is being called by the `before_action` line: https://github.com/Kellyreid/mtgtest/blob/master/app/controllers/transactions_controller.rb#L2

If `Transaction` should always be scoped to the user, you can change `set_transaction` to something like the following (I didn't test this, but something close to this):

```ruby
def set_transaction
  @transaction = current_user.transactions.find(params[:id])
end
```

**Comment by Kellyreid** [comment]
What exactly does the method set_transaction do?

**Comment by Kellyreid** [comment]
nevermind, i think i understand.  I made the change you suggested and now
it seems to work.

**Comment by ssorallen** [comment]
The `@` before a variable in Rails is a request variable. After calling `set_transaction`, there's a variable called `@transaction` in the request scope that ends up being used in your view.

**Comment by Kellyreid** [comment]
ok, so its kind of like the 'current' object, that we're working with, and
a way to refer to its attributes?
